### ISSUE TITLE
运行 ds_finetune_superglue.sh  key error "dev-0"

### ISSUE THREAD

**Issue by lulia0228** [THUDM/GLM#101]
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/49608151/221748713-4523b0ed-f482-4ab3-831a-7be82d3b47d2.png">

tasks/eval_utils.py", line 203, in multichoice_evaluate...

**Comment by duzx16** [comment]
是否设置了`MP_SIZE`>1？跟 #107 应该是相同的原因。目前已修复。
