### ISSUE TITLE
dockerfile中的ssh-env-config.sh文件怎么配置

### ISSUE THREAD

**Issue by lulia0228** [THUDM/GLM#104]
COPY ssh-env-config.sh /usr/local/bin/ssh-env-config.sh

哈喽，这个文件可以简单示例一下吗？

**Comment by duzx16** [comment]
这个文件是https://github.com/buildkite/docker-ssh-env-config

**Comment by lulia0228** [comment]
> 这个文件是https://github.com/buildkite/docker-ssh-env-config

感谢回复
