### ISSUE TITLE
`glm-10b-chinese` `build_inputs_for_generation` missing `targets` argument

### ISSUE THREAD

**Issue by larrylawl** [THUDM/GLM#108]
Hi, thanks for the great work!

`build_inputs_for_generation` for `glm-10b-chinese` does not take in `targets` argument. Link [here](https://huggingface.co/THUDM/glm-10b-chinese/blob/main/tokenization_glm.py).

This is inconsistent with `glm-large-chinese`, which supports `targets` argument. Link [here](https://huggingface.co/THUDM/glm-large-chinese/blob/main/tokenization_glm.py)

Can `glm-10b-chinese` support the `targets` argument please? Thank you!

**Comment by duzx16** [comment]
Thank you for pointing that out. Already fixed.
