### ISSUE TITLE
怎么使用batch beam search

### ISSUE THREAD

**Issue by Mryangkaitong** [THUDM/GLM#110]
如题：一个一个样本使用beam search解码时没有问题：

` texts = ["家长对幼儿园孩子情况评价怎么写? [gMASK]", "中国女生与外国的女生有什么区别? [gMASK]"]
 inputs = tokenizer(texts[:1], padding=True, return_tensors="pt")
inputs = tokenizer.build_inputs_for_generation(inputs, max_gen_length=512)
outputs = model.generate(**inputs, max_length=512, eos_token_id=tokenizer.eop_token_id,  num_beams=4, no_repeat_n    gram_size=7, repetition_penalty=1.1, min_length=3)
`

但是一个一个使用beam search解码时间太慢，想要组一个batch进行同时解码：

` texts = ["家长对幼儿园孩子情况评价怎么写? [gMASK]", "中国女生与外国的女生有什么区别? [gMASK]"]
 inputs = tokenizer(texts, padding=True, return_tensors="pt")
inputs = tokenizer.build_inputs_for_generation(inputs, max_gen_length=512)
outputs = model.generate(**inputs, max_length=512, eos_token_id=tokenizer.eop_token_id,  num_beams=4, no_repeat_n    gram_size=7, repetition_penalty=1.1, min_length=3)
`
会报错：
<img width="1231" alt="截屏2023-03-01 下午11 50 23" src="https://user-images.githubusercontent.com/23132307/222191162-49d96943-defd-4d4d-9c20-64b56189f414.png">

而默认不使用beam search又可以batch解码（好像是使用的最大贪婪解码）
` texts = ["家长对幼儿园孩子情况评价怎么写? [gMASK]", "中国女生与外国的女生有什么区别? [gMASK]"]
 inputs = tokenizer(texts, padding=True, return_tensors="pt")
inputs = tokenizer.build_inputs_for_generation(inputs, max_gen_length=512)
outputs = model.generate(**inputs, max_length=512, eos_token_id=tokenizer.eop_token_id)
`
现在的问题是想用beam search batch解码，请问这个怎么解决呢？感谢

**Comment by taofennanhai** [comment]
这个我也碰到了，是因为输入的inputs_id和位置编码的维度对应不上。目前还没见到作者如何解决。

**Comment by duzx16** [comment]
已修复。请从https://huggingface.co/models?other=glm,thudm获得最新的实现。

**Comment by Mryangkaitong** [comment]
非常感谢，确实可以跑了，但是还是有两个问题：（1）batch后时间并没有缩短（2）batch后样本的beam search输出和单个解码输出不一致了。

测试的代码[inference_batch函数代表batch解码，inference_single函数代表一个一个去解码]如下：

<img width="1330" alt="截屏2023-03-03 下午1 06 35" src="https://user-images.githubusercontent.com/23132307/222636247-bd687f38-1d71-4ec1-8158-a3a5126925bb.png">

（1）其中inference_batch函数的输出：

`2023-03-03 12:59:27
2023-03-03 13:03:35
['[CLS] 家长对幼儿园孩子情况评价怎么写? [gMASK] <|endoftext|> <|endoftext|> <|endoftext|> <|startofpiece|> 家长对幼儿园孩子情况评价怎么写,家长对幼儿园孩子情况评价,家长对幼儿园孩子情况的评价,家长对幼儿园孩子的评价,家长对幼儿园的评价,家长对幼儿园孩子的评价。家长对幼儿园孩子情况的评价怎么写?家长对幼儿园孩子情况的评价,家长对幼儿园孩子情况的评论,家长对幼儿园孩子的评论,家长对幼儿园的评价。家长对幼儿园孩子情况的评论怎么写?家长对幼儿园孩子情况的评论。家长对幼儿园孩子的评价怎么写?家长对幼儿园孩子的评论。家长对幼儿园的评价怎么写?家长对幼儿园的评价。 <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|>', '[CLS] 有哪些网站,一旦知道你就离不开了? [gMASK] <|endoftext|> <|startofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|> <|endofpiece|>', '[CLS] 水果的一些好处 [gMASK] <|endoftext|> <|endoftext|> <|endoftext|> <|endoftext|> <|endoftext|> <|endoftext|> <|endoftext|> <|endoftext|> <|startofpiece|> : 1、水果中含有人体必需的多种维生素、矿物质、碳水化合物、粗纤维、蛋白质及脂肪等营养素,能促进身体健康,进而达到防治疾病的效果。 2、水果中含有多种有机酸、芳香物质、色素等,能刺激消化液分泌,增进食欲,有助于食物的消化与吸收。 3、水果中含有果胶,果胶有保护肠壁、活化肠内有用的细菌、调整胃肠功能的作用,所以它能够有效地清理肠道,预防便秘。 4、水果中含有大量的纤维素,能促进肠道蠕动,增加粪便体积,缩短粪便在肠道内滞留的时间,减少肠道对毒素的吸收,预防结肠癌的发生。 5、水果中含有丰富的维生素c,能降低血液中的胆固醇及三酸甘油脂,使血中胆固醇及三酸甘油脂的含量降低,对防治心血管疾病有良好的作用。 6、水果中含有果胶及纤维,有降低血中胆固醇作用,可减少脂肪在血管内壁的滞留时间,故可用来防治动脉粥样硬化、冠心病及高血压。 7、水果中含有钾,钾能维持细胞内的渗透压,参与能量代谢过程,维持神经肌肉正常的兴奋性,缺钾会引致疲劳无力、心跳减弱、头昏眼花、恶心呕吐、腹胀腹泻、心律失常等。 8、水果中含有镁,镁是维持心脏正常功能的重要元素,具有调节神经和肌肉活动、增强耐久力的神奇功能。 9、水果中含有铁,铁是构成血红蛋白的主要成分,缺铁会引致缺铁性贫血。 10、水果中含有铜,铜是人体健康不可缺少的微量营养素,对于血液、中枢神经和免疫系统,头发、皮肤和骨骼组织以及脑子和肝、心等内脏的发育和功能有重要影响。 <|endofpiece|>']`

可以看到开始和结束的两个时间点是2023-03-03 12:59:27和2023-03-03 13:03:35，耗时大概是4min多


（2）其中inference_single函数的输出：

`2023-03-03 13:03:35
2023-03-03 13:03:37
['[CLS] 家长对幼儿园孩子情况评价怎么写? [gMASK] <|endoftext|> <|startofpiece|> 家长对幼儿园孩子情况评价怎么写,家长对幼儿园孩子情况评价,家长对幼儿园孩子情况的评价,家长对幼儿园孩子的评价,家长对幼儿园孩子的情况,家长对幼儿园孩子的评价。 <|endofpiece|>']
2023-03-03 13:03:37
2023-03-03 13:03:38
['[CLS] 有哪些网站,一旦知道你就离不开了? [gMASK] <|endoftext|> <|startofpiece|> <|endofpiece|>']
2023-03-03 13:03:38
2023-03-03 13:05:04
['[CLS] 水果的一些好处 [gMASK] <|endoftext|> <|startofpiece|> : 1、水果中含有人体必需的多种维生素、矿物质、碳水化合物、粗纤维、蛋白质及脂肪等营养素,能促进身体健康,进而达到防治疾病的效果。 2、水果中含有多种有机酸、芳香物质、色素等,能刺激消化液分泌,增进食欲,有助于食物的消化与吸收。 3、水果中含有果胶,果胶有保护肠壁、活化肠内有用的细菌、调整胃肠功能的作用,所以它能够有效地清理肠道,预防便秘。 4、水果中含有大量的纤维素,能促进肠道蠕动,增加粪便体积,缩短粪便在肠道内滞留的时间,减少肠道对毒素的吸收,预防结肠癌的发生。 5、水果中含有丰富的维生素c,能降低血液中的胆固醇,进而达到预防心脏病的效果。 6、水果中含有大量的果胶,果胶是一种可溶性的纤维质,能促进胆固醇代谢,进而达到降低血脂的效果。 7、水果中含有大量的钾,钾能维持细胞内的渗透压,参与能量代谢及维持神经肌肉正常的兴奋性,缺钾会引致神经肌肉兴奋性增高,造成心跳加速、全身无力,严重者可导致心跳停止而死亡。 8、水果中含有大量的镁,镁是维持心脏正常功能的重要元素,缺镁会引致心血管病变。 9、水果中含有大量的钙,钙是构成骨骼和牙齿的主要成分,缺钙会引致骨质疏松症。 10、水果中含有大量的铁,铁是构成血红蛋白的主要成分,缺铁会引致缺铁性贫血。 11、水果中含有大量的磷,磷是构成骨骼、牙齿的主要成分,缺磷会引致佝偻病。 12、水果中含有大量的铜,铜是合成血红蛋白的必需物质,缺铜会引致贫血。 13、水果中含有大量的锌,锌是构成味觉素的主要成分,缺锌会引致味觉减退。 14、水果中含有大量的硒,硒是维持肌体正常生命活动不可缺少的微量元素,缺硒会引致身体虚弱。 15、水果中含有大量的维生素a,维生素a是构成视觉细胞内感光物质的重要成分,缺乏维生素a会引致夜盲症。 16、水果中含有大量的b族维生素,b族维生素是推动体内代谢,把糖、脂肪、蛋白质等转化成热量时不可缺少的物质,缺乏b族维生素会引致代谢障碍。 17、水果中含有大量的维生素e,维生素e是维持生殖器官正常机能不可缺少的物质,缺乏维生素e会引致生殖机能障碍。 18、水果中含有大量的维生素k,维生素k是止血的重要物质,缺乏维生素k']`

可以看到所有样本加起来生成过程的总耗时不到2min。

**最终的目的是想单个解码太慢，想batch化**，但是目前看好像batch化后更慢了；而且结果也对不齐，作者能帮忙看看这里是咋回事吗？或者说怎么优化batch使得结果生成可以并行化进而加快速度。非常感谢🙏

**Comment by Mryangkaitong** [comment]
> batch之后变慢了是因为单个样本的时候每个样本只要生成结束就可以停止推理，但是在batch之后必须要等生成长度最长的样本生成结束才能停止推理。所以用batch加速不适合样本间生成长度差别很大的情况。
> 生成结果的差异应该是因为batch之后GPU的计算精度导致的。

嗯嗯，假设一个batch的样本是A,B,C,D。其生成的样本长度大小关系是response_length(A)>response_length(B), response_length(C)>response_length(D)；理论上耗时是time(A) > time(B) >  time(C) >  time(D)，当单个进行解码时，总耗时是time(A) + time(B) +  time(C) +  time(D)；但是batch后是time(A)；所以理论上batch化后的时间节约是 time(B) +  time(C) +  time(D)，那为什么会变长呢时间？或者“用batch加速不适合样本间生成长度差别很大的情况”这句话怎么理解呢？
