### ISSUE TITLE
模型并行训练结束后，如何将多个模型文件合并成一个？

### ISSUE THREAD

**Issue by sduhkn** [THUDM/GLM#137]
通过`change_mp.py` 将10B模型拆封成N份，finetune之后得到N个部分模型文件，请问如何将N个部分模型文件合并，没找到这部分代码。

**Comment by N-Kingsley** [comment]
你好问下，change_mp.py怎么将10B模型拆封成N份，代码会报如下错误：
![image](https://user-images.githubusercontent.com/38311217/232743107-9ddde2be-71bf-4299-8647-4bc649f4aab6.png)

**Comment by wangerxiao001** [comment]
> 通过`change_mp.py` 将10B模型拆封成N份，finetune之后得到N个部分模型文件，请问如何将N个部分模型文件合并，没找到这部分代码。

请问这个解决了吗
