### ISSUE TITLE
Can you provide the test.json file mentioned in TestDataset in data_utils/corpora.py？ 

### ISSUE THREAD

**Issue by zfq-hit** [THUDM/GLM#16]
I think this file(test.json) is small and  is very important for running pretraining code. Thank you very much!!!

**Comment by duzx16** [comment]
It is a jsonl (https://jsonlines.org/) file with the format
```
{"prompt": "", "text": ...}
{"prompt": "", "text": ...}
...
```
where the `text` key corresponds to a document. You can process the data you want to pretrain on into the format.

**Comment by zfq-hit** [comment]
Thank you very much!!!
