### ISSUE TITLE
Evaluation on SQuAD

### ISSUE THREAD

**Issue by SeonggwanAhn** [THUDM/GLM#19]
Hello.
I want to ask you 2 things.

1. Evaluate GLM on SQuAD task for EM(Exact Match)/F1 to reproduce Table 10 results in your paper .
  Following your code, which task (seq2seq/supergue) you evaluate is ambiguous.
  If you evaluated on seq2seq task, there's no source code for metric(EM/F1).
  And if you evaluated on superglue task, It doesn't make sense to measure EM/F1 because your code's metric for 'squad' is on accuracy_metric.
  So, how did you get SQuAD task results (EM/F1) in Table 10 in your paper? (what command or path the code is executed?)

2. How to implement blank-infilling task with no label/candidates for superglue task.
  (1) Based on your code, when the task is `multi_token=True`, you just implemented `get_labels()` returns only `['0']`.
  I wonder what the part(`get_labels()` returns `['0']`) means.
  (2) I checked you implemented `SquadPVP, CMRCPVP(tasks/superglue/pvp.py)` which have no labels/candidates.
  But when I actually run Squad task in superglue directory, **the model predicts only label(0) not things like token IDs.**
  So I don't know how to implement such a case for getting token IDs by blank-infilling task in the superglue code. 

Thanks

**Comment by thomas0809** [comment]
Hi,

Thanks for your question! SQuAD is implemented as a seq2seq generation task. Example script:
```
bash scripts/ds_finetune_seq2seq.sh \ 
   config_tasks/model_blocklm_base.sh \ 
   config_tasks/seq_squad_v1.sh
```
The evaluation code is [here](https://github.com/THUDM/GLM/blob/main/tasks/seq2seq/finetune.py#L97).
