### ISSUE TITLE
attention mask between spans

### ISSUE THREAD

**Issue by ChuanTianML** [THUDM/GLM#20]
**When predicting x3, can the model see [x5, x6] ?
The attention mask figure (d) seems to say yes.**
![image](https://user-images.githubusercontent.com/38931763/174469296-e3257040-d6dc-47b9-a6c6-37ab543490bd.png)

**Comment by duzx16** [comment]
Yes. Note that according to section 2.1.1, the order to predict [x3] and [x5, x6] are randomly shuffled.
