### ISSUE TITLE
If the data of a row exceeds 512, will the excess part be discarded?

### ISSUE THREAD

**Issue by Aurora-slz** [THUDM/GLM#22]
Excuse me, I read the function `def get_item()` in class `BlockDatast` and found it only intercept 512 tokens. So is the rest of it discarded?

(I doubt this statement, because there are two data segments from the same input data)

Thanks for your solution!

**Comment by duzx16** [comment]
The get_item method will randomly select a continuous segment of 512 tokens if the document is longer than 512 tokens, and concatenate multiple documents if the  document is shorter than 512 tokens.
You can ignore the `loss_mask` data segment. It is originally designed to deal with the prompt part in a document that should not be learned by the model, and never used in GLM pretraining.
