### ISSUE TITLE
GLM-2B-Chinese Pretrained Model please

### ISSUE THREAD

**Issue by lockmatrix** [THUDM/GLM#26]
I think it is suitable for Apple silicon M2 24G memory

**Comment by Xiao9905** [comment]
@lockmatrix Hi,

Thanks for your interest in GLM. Unfortunately, we didn't pre-train a 2B Chinese version. Maybe a feasible solution is to use quantization (e.g., 8 bit) for model compression from tools like [BMInf](https://github.com/OpenBMB/BMInf), which can compress a 10B model's memory usage from about 36G to 18G and accelerate the inference as well.

We are also working on the quantization of GLM-10B, and if your time permits please wait for our news. Thanks!
