### ISSUE TITLE
有没有模型压缩量化等方法提高模型的推理性能

### ISSUE THREAD

**Issue by jiangliqin** [THUDM/GLM#27]
你好，感谢开源GLM大模型，目前在V100上文本生成推理相应在1-2min间，有没有模型压缩等方法提高推理性能？

**Comment by Xiao9905** [comment]
@jiangliqin 你好，

感谢你对于GLM系列工作的兴趣。我们正在进行量化相关的工作，敬请期待。

**Comment by jiangliqin** [comment]
请问GLM10B 可以用FasterTransformer加速推理吗？

**Comment by jiangliqin** [comment]
请问GLM-130B中的量化方法适用吗？
