### ISSUE TITLE
generate有没有并行的方法

### ISSUE THREAD

**Issue by debby1103** [THUDM/GLM#33]
观察到generate_samples没有提供批生成的接口，只能作为demo使用，不知道有没有较为快捷的方法？谢谢！

**Comment by duzx16** [comment]
我们最近在HuggingFace hub上上传了GLM-10B等模型，欢迎使用

**Comment by duzx16** [comment]
> > 我们最近在HuggingFace hub上上传了GLM-10B等模型，欢迎使用
> 
> 您好！对于预测来讲，多少的gpu及显存大小、内存够用？我的机器配置是2*3090ti 24gb，不知道能不能加载运行

@ScottishFold007 大概需要占用20G的显存，用一张3090Ti可以运行
