### ISSUE TITLE
模型权重加载问题

### ISSUE THREAD

**Issue by maojinyang** [THUDM/GLM#41]
在进一步预训练时执行模型加载的时候报错：
~~~
RuntimeError: Error(s) in loading state_dict for GLMModel:
	Missing key(s) in state_dict: "word_embeddings.weight", "transformer.block_position_embeddings.weight". 
	Unexpected key(s) in state_dict: "mixins.block_position_embedding.block_position_embeddings.weight", "transformer.word_embeddings.weight". 
~~~
模型是在经过`change_mp.py`切分为4片之后的模型

**Comment by duzx16** [comment]
这个checkpoint的是从SwissArmyTransformer的仓库下载的吗？模型的格式有一点不一样，你把state_dict里面`transformer.word_embeddings.weight`改成`word_embeddings.weight`，`mixins.block_position_embedding.block_position_embeddings.weight`改成`transformer.block_position_embeddings.weight`就好了

**Comment by maojinyang** [comment]
模型就是从这个项目里的README文档中的链接下载的，就是GLM-XXLarge-Chinese所对应的链接 [apply here](https://wudaoai.cn/model/download?resourceId=1420992103650996224&filename=GLM-10B-zh.tar.bz2)
感谢您的回答！
