### ISSUE TITLE
Information about those new released multi-task model

### ISSUE THREAD

**Issue by siriusctrl** [THUDM/GLM#44]
Hi there,

I wonder whether there is documentation about the newly released multi-task model checkpoint. For example, explaining whether it is trained on the multi-lingual dataset and how those models are trained (in terms of multi-task).

Thanks in advance.

**Comment by duzx16** [comment]
The model denoted with "multi-task" means it is trained with a mixture of the token-level and document level objectives. It is called "multi-task" because it can be used for both NLU and generation tasks. Sorry for the misunderstanding. We already updated the model table.
