### ISSUE TITLE
convert pretrained pt to huggingface

### ISSUE THREAD

**Issue by xv44586** [THUDM/GLM#51]
thanks your work.
I fine-tune it at my own dataset and now I want to convert it to your huggingcace format.
can you share the script that you used to convert pretrained pt to the huggingface ?

**Comment by duzx16** [comment]
You can use `scripts/convert_glm_checkpoint_to_transformers.py` to convert the checkpoint
```shell
python scripts/convert_glm_checkpoint_to_transformers.py CHECKPOINT_PATH MODEL_NAME
```
where `CHECKPOINT_PATH` is the path to the `mp_rank_00_model_states.pt` file and MODEL_NAME is the repo name on huggingface hub (should be in `["glm-large", "glm-roberta-large", "glm-large-chinese", "glm-515m", "glm-2b", "glm-10b", "glm-10b-chinese"]`)
