### ISSUE TITLE
Unable to use `AutoModelForSeq2SeqLM`

### ISSUE THREAD

**Issue by larrylawl** [THUDM/GLM#52]
Hi, I tried to use `AutoModelForSeq2SeqLM` as described in your README. However, I faced this error. Can you please advice? Thank you!

![image](https://user-images.githubusercontent.com/40198156/206986564-d58001e5-a8b4-4fa3-aaff-9cdf3157348c.png)

**Comment by duzx16** [comment]
Could you please check the version of your `transformers` package? You should install `transformers>=4.23.1` to run the GLM model.

**Comment by duzx16** [comment]
Sorry. Already fixed the bug.
