### ISSUE TITLE
Which config is used to pretrain the released `GLM-10B-Chinese` model? is `ds_block_10B_chinese_longer.sh` or `ds_block_10B_chinese.sh`

### ISSUE THREAD

**Issue by silverriver** [THUDM/GLM#53]
Hi, I am wondering which config did you use to pretrain the released `GLM-10B-Chinese` model?

It seems that you released two configs: `ds_block_10B_chinese_longer.sh` and `ds_block_10B_chinese.sh`.

Which one is used to produce the released `GLM-10B-Chinese` ckpt?

is 

```bash
bash scripts/ds_pretrain_nvidia.sh config/ds_block_10B_chinese_longer.sh
```

or 

```bash
bash scripts/ds_pretrain_nvidia.sh config/ds_block_10B_chinese.sh
```

When is `ds_block_10B_chinese_longer.sh` used?

**Comment by duzx16** [comment]
To maximize the utility of computational resources,  GLM-10B-Chinese is trained with two stages. In the first stage we set `seq-length` to 512 (`ds_block_10B_chinese.sh`) and in the second stage we set `seq-length` to 1024 (`ds_block_10B_chinese_longer.sh`).
