### ISSUE TITLE
Hello, below are some questions I encountered while learning code, I hope you can answer them when you have time, thank you.

### ISSUE THREAD

**Issue by Ant0082** [THUDM/GLM#58]
1. The tutorial for DeepSpeed suggests using "deepspeed.initdistributed" to replace "torch.distributed.initprocessgroup", but the code in "finetune_glm.py" still uses "torch.distributed.initprocessgroup". Is this code correct?

**Comment by duzx16** [comment]
The code is completed with DeepSpeed 0.4.0, when there is no `deepspeed.initdistributed` method. According to our test the code can run under DeepSpeed 0.5.9. You can also replace `torch.distributed.initprocessgroup` with `deepspeed.initdistributed` for newer versions.
