### ISSUE TITLE
Can not reproduce SQuAD v1.1 result using GLM-Large

### ISSUE THREAD

**Issue by cklsoft** [THUDM/GLM#63]
Hi,
    I tried to reproduce Table 10 in paper. The GLM-Large model was downloaded from [this](https://cloud.tsinghua.edu.cn/d/13f5b03da9594e5490c4/files/?p=%2Fglm-large-generation.tar.bz2). I've tried different learning rates (from 3e-6 ~ 5e-5). However, the best result is only 90.5 (91.9 is reported in Table 10). 

The command to run training SQuAD v1.1 is:
```
MODEL_CONFIG=config_tasks/model_blocklm_large_generation.sh
TASK_CONFIG=config_tasks/seq_squad_v1.sh

bash scripts/finetune_seq2seq.sh $MODEL_CONFIG $TASK_CONFIG
```

The training parameters are:

```
python -u finetune_glm.py --local_rank=0 --finetune --experiment-name generation-large-squad_v1-3e-6 --task squad_v1 --data-dir task_data/SQuAD --save inetune_checkpoints --checkpoint-activations --epochs 5 --batch-size 12 --lr 3e-6 --block-lm --num-layers 24 --hidden-size 1024 --num-attention-heads 16 --max-position-embeddings 512 --tokenizer-model-type bert-large-uncased --tokenizer-type BertWordPieceTokenizer --load-pretrained blocklm-large-generation --lr-decay-style linear --warmup 0.06 --weight-decay 1.0e-1 --label-smoothing 0.1 --save-interval 10000 --log-interval 200 --eval-interval 1000 --eval-iters 100 --eval-epoch 1 --overwrite --src-seq-length 512 --tgt-seq-length 64 --min-tgt-length 0 --length-penalty 0 --num-beams 5 --select-topk --eval-batch-size 8 --validation-metric F1
```

The total batch size used is 12 and it's trained on 1 GPU.

By the way, the md5 of `glm-large-blank.tar.bz2` and `glm-large-generation.tar.bz2` in Tsinghua-Cloud are the same.

**Comment by duzx16** [comment]
The md5 of `glm-large-blank.tar.bz2`(`e9025e2f4eb598f0d4ef5c3c2826b0c6`) and `glm-large-generation.tar.bz2`(`59cdd3fcf126655e38e4bb1b4bf2998e`) are different. Are you sure you downloaded the correct checkpoint? The `GLM-Large` in the paper is `glm-large-blank.tar.bz2`.
