### ISSUE TITLE
Model Warmup for ICL

### ISSUE THREAD

**Issue by Ant0082** [THUDM/GLM#64]
你好，想微调一下GLM-10B-Chinese用于ICL，收集了几种任务的数据，其中一个任务是问答，构造的示例为下面这种格式：

```cmd
下面是几组问答。
A：中国的首都是哪里？
B：北京
A：美国的首都是哪里？
B：华盛顿
A：英国的首都是哪里？
B：[MASK]
上面几组问答都与地理知识相关
```

使用的运行脚本为：
```cmd
bash scripts/ds_finetune_seq2seq.sh  config_tasks/model_blocklm_10B_chinese.sh  config_tasks/seq_customization.sh
```

疑问：
在阅读代码过程中，GLM/tasks/seq2seq/dataset.py 中都几种DataSet但好像都与上面的“示例”格式不太匹配
1. CustomizationDataset是手动在Source的后面添加Mask_id
2. BlankLMDataset是预处理添加的[MASK]，而且一个[MASK]对应一个token id，而上面“示例”中的 [MASK]可能代表一句话

像类似这种情况，需要自己写一个DataSet吗？仿照CustomizationDataset，预先添加好[mask]，然后去掉手动在末尾添加mask_id，这样处理可以不？

**Comment by Ant0082** [comment]
另外一个问题是怎样将训练好的模型权值文件转为huggingface可以加载的权值文件，代码可以分享下吗？

**Comment by duzx16** [comment]
可以
可以用`scripts/convert_glm_checkpoint_to_transformers.py`来将仓库中的模型checkpoint转化为huggingface格式
```shell
python scripts/convert_glm_checkpoint_to_transformers.py CHECKPOINT_PATH MODEL_NAME
```
where `CHECKPOINT_PATH` is the path to the `mp_rank_00_model_states.pt` file and MODEL_NAME is the repo name on huggingface hub (should be in `["glm-large", "glm-roberta-large", "glm-large-chinese", "glm-515m", "glm-2b", "glm-10b", "glm-10b-chinese"]`). The `pytorch_model.bin` will be saved under the same directory as `mp_rank_00_model_states.pt`.
