### ISSUE TITLE
glm-10B-chinese是如何finetune的，运行的脚本文件是哪个

### ISSUE THREAD

**Issue by haiqizhang** [THUDM/GLM#69]
glm-10B-chinese的pretrained_model已有，请问finetune过程是如何运行的（运行哪个脚本文件呢），finetune的数据集还是WuDao的吗，数据集的大小是多大？

**Comment by siyuanxue** [comment]
1.主页下面展示了各种不同任务finetune的demo可以认真找下需要哪种任务的
2.finetune数据集看自己需求吧，通常需要五个epoch以上才有好写的效果，数据集大了可能要finetune很久
