### ISSUE TITLE
How are the escape characters '\n' or '\t' in data processed during pretraining or finetuing?

### ISSUE THREAD

**Issue by Tebmer** [THUDM/GLM#72]
Hi,

I have a question that how are the escape characters '\n' or '\t' in data processed during pretraining or finetuing? 

I use the glm tokenizer and find that those escape characters are ignored when encoding.
```python
(Pdb) tokenizer.EncodeAsIds("Hello \n world").tokenization
# Output: [712, 25708, 17487]
(Pdb) tokenizer.EncodeAsIds("Hello world").tokenization
# Output: [712, 25708, 17487]
```
Do you transfer these escape characters to some special tokens when preprocessing data, and thus keep them?

Thanks!

**Comment by duzx16** [comment]
Which model are you testing on? Different models may have different tokenizers (to align with the baseline models).

**Comment by Tebmer** [comment]
> 

I use the "glm-10b-chinese".

**Comment by duzx16** [comment]
> ```python
> Hello \n world
> ```

You can use <n> to replace '\n'. '\t' is considered as normal space so there is no way to keep it.

**Comment by Tebmer** [comment]
Ok. Thanks for your suggestion. 

> Which model are you testing on? Different models may have different tokenizers (to align with the baseline models).

So, I wonder if there is any other tokenizer can keep these escape characters like '\n'. '\t' ?

**Comment by Tebmer** [comment]
> 
> You can use <n> to replace '\n'. '\t' is considered as normal space so there is no way to keep it.
> ```

And, do you preprocess your pre-training data like this way during the pre-training stage?

**Comment by duzx16** [comment]
The tokenizers of glm-roberta-large, glm-2b, and glm-10b

**Comment by duzx16** [comment]
> > You can use  to replace '\n'. '\t' is considered as normal space so there is no way to keep it.
> 
> And, do you preprocess your pre-training data like this way during the pre-training stage?

Yes

**Comment by Tebmer** [comment]
I get it! Thanks for your patience!
