### ISSUE TITLE
How to finetune for text generation?

### ISSUE THREAD

**Issue by ouyangliqi** [THUDM/GLM#79]
Thanks for your great work. I have a question for tuning text generation task. According to the tutorial in README.md, I guess the usage might be something like this. If there is an error, please help me correct it, thanks.

```
# Training
inputs = tokenizer(
    ["Tsinghua [gMASK] University is located in Beijing."],
    return_tensors="pt", padding=True)
inputs = tokenizer.build_inputs_for_generation(inputs, targets=["Tsinghua University is located in Beijing."], max_gen_length=8, padding=False)
inputs = inputs.to('cuda')
outputs = model(**inputs)
loss = outputs.loss
logits = outputs.logits
```

**Comment by duzx16** [comment]
Yes, you can get the training loss in this way. To finetune the mode, you still need other codes like dataloading, optimizer, etc.

**Comment by ouyangliqi** [comment]
Thanks!

**Comment by ouyangliqi** [comment]
The code in tuturial seems not work.  



```
>>> inputs = tokenizer(
...     ["Tsinghua University is located in [MASK].", "One minus one equals zero, is it correct? Answer: [MASK]"],
...     return_tensors="pt", padding=True)
>>> inputs = tokenizer.build_inputs_for_generation(inputs, targets=["Beijing", "No"], max_gen_length=8, padding=False)
>>> outputs = model(**inputs)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <stdin>:1 in <module>                                                                            │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/m │
│ odule.py:1110 in _call_impl                                                                      │
│                                                                                                  │
│   1107 │   │   # this function, and just call forward.                                           │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1111 │   │   # Do not call functions when jit is used                                          │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
│ 893 in forward                                                                                   │
│                                                                                                  │
│   890 │   │   │   mems=None,                                                                     │
│   891 │   │   │   **kwargs                                                                       │
│   892 │   ):                                                                                     │
│ ❱ 893 │   │   model_output = self.glm.forward(input_ids, position_ids, attention_mask, mems=me   │
│   894 │   │   lm_logits = model_output.logits                                                    │
│   895 │   │   loss = None                                                                        │
│   896 │   │   if labels is not None:                                                             │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
│ 769 in forward                                                                                   │
│                                                                                                  │
│   766 │   │   │   **kwargs                                                                       │
│   767 │   ):                                                                                     │
│   768 │   │   batch_size = input_ids.size(0)                                                     │
│ ❱ 769 │   │   words_embeddings = self.word_embeddings(input_ids)                                 │
│   770 │   │   embeddings = words_embeddings                                                      │
│   771 │   │                                                                                      │
│   772 │   │   device = input_ids.device                                                          │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/m │
│ odule.py:1110 in _call_impl                                                                      │
│                                                                                                  │
│   1107 │   │   # this function, and just call forward.                                           │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1111 │   │   # Do not call functions when jit is used                                          │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
│ 185 in forward                                                                                   │
│                                                                                                  │
│   182 │                                                                                          │
│   183 │   def forward(self, input_):                                                             │
│   184 │   │   # Get the embeddings.                                                              │
│ ❱ 185 │   │   output = F.embedding(input_, self.weight,                                          │
│   186 │   │   │   │   │   │   │    self.padding_idx, self.max_norm,                              │
│   187 │   │   │   │   │   │   │    self.norm_type, self.scale_grad_by_freq,                      │
│   188 │   │   │   │   │   │   │    self.sparse)                                                  │
│                                                                                                  │
│ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/functiona │
│ l.py:2183 in embedding                                                                           │
│                                                                                                  │
│   2180 │   │   #   torch.embedding_renorm_                                                       │
│   2181 │   │   # remove once script supports set_grad_enabled                                    │
│   2182 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
│ ❱ 2183 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
│   2184                                                                                           │
│   2185                                                                                           │
│   2186 def embedding_bag(                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: index out of range in self
```

**Comment by duzx16** [comment]
> The code in tuturial seems not work. @duzx16
> 
> ```
> >>> inputs = tokenizer(
> ...     ["Tsinghua University is located in [MASK].", "One minus one equals zero, is it correct? Answer: [MASK]"],
> ...     return_tensors="pt", padding=True)
> >>> inputs = tokenizer.build_inputs_for_generation(inputs, targets=["Beijing", "No"], max_gen_length=8, padding=False)
> >>> outputs = model(**inputs)
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ <stdin>:1 in <module>                                                                            │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/m │
> │ odule.py:1110 in _call_impl                                                                      │
> │                                                                                                  │
> │   1107 │   │   # this function, and just call forward.                                           │
> │   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
> │   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
> │ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                                         │
> │   1111 │   │   # Do not call functions when jit is used                                          │
> │   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
> │   1113 │   │   if self._backward_hooks or _global_backward_hooks:                                │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
> │ 893 in forward                                                                                   │
> │                                                                                                  │
> │   890 │   │   │   mems=None,                                                                     │
> │   891 │   │   │   **kwargs                                                                       │
> │   892 │   ):                                                                                     │
> │ ❱ 893 │   │   model_output = self.glm.forward(input_ids, position_ids, attention_mask, mems=me   │
> │   894 │   │   lm_logits = model_output.logits                                                    │
> │   895 │   │   loss = None                                                                        │
> │   896 │   │   if labels is not None:                                                             │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
> │ 769 in forward                                                                                   │
> │                                                                                                  │
> │   766 │   │   │   **kwargs                                                                       │
> │   767 │   ):                                                                                     │
> │   768 │   │   batch_size = input_ids.size(0)                                                     │
> │ ❱ 769 │   │   words_embeddings = self.word_embeddings(input_ids)                                 │
> │   770 │   │   embeddings = words_embeddings                                                      │
> │   771 │   │                                                                                      │
> │   772 │   │   device = input_ids.device                                                          │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/m │
> │ odule.py:1110 in _call_impl                                                                      │
> │                                                                                                  │
> │   1107 │   │   # this function, and just call forward.                                           │
> │   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
> │   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
> │ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                                         │
> │   1111 │   │   # Do not call functions when jit is used                                          │
> │   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
> │   1113 │   │   if self._backward_hooks or _global_backward_hooks:                                │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/.cache/huggingface/modules/transformers_modules/local/modeling_glm.py: │
> │ 185 in forward                                                                                   │
> │                                                                                                  │
> │   182 │                                                                                          │
> │   183 │   def forward(self, input_):                                                             │
> │   184 │   │   # Get the embeddings.                                                              │
> │ ❱ 185 │   │   output = F.embedding(input_, self.weight,                                          │
> │   186 │   │   │   │   │   │   │    self.padding_idx, self.max_norm,                              │
> │   187 │   │   │   │   │   │   │    self.norm_type, self.scale_grad_by_freq,                      │
> │   188 │   │   │   │   │   │   │    self.sparse)                                                  │
> │                                                                                                  │
> │ /mnt/datadisk0/ouyangliqi/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/functiona │
> │ l.py:2183 in embedding                                                                           │
> │                                                                                                  │
> │   2180 │   │   #   torch.embedding_renorm_                                                       │
> │   2181 │   │   # remove once script supports set_grad_enabled                                    │
> │   2182 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
> │ ❱ 2183 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
> │   2184                                                                                           │
> │   2185                                                                                           │
> │   2186 def embedding_bag(                                                                        │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> IndexError: index out of range in self
> ```

Which model are you using?

**Comment by ouyangliqi** [comment]
model = AutoModelForSeq2SeqLM.from_pretrained("BAAI/glm-10b", trust_remote_code=True)

I download the files from huggingface, and use the local files instead. (https://huggingface.co/BAAI/glm-10b-chinese/tree/main)

**Comment by duzx16** [comment]
> inputs = tokenizer(
>     ["Tsinghua [gMASK] University is located in Beijing."],
>     return_tensors="pt", padding=True)
> inputs = tokenizer.build_inputs_for_generation(inputs, targets=["Tsinghua University is located in Beijing."], max_gen_length=8, padding=False)
> inputs = inputs.to('cuda')
> outputs = model(**inputs)
> loss = outputs.loss
> logits = outputs.logits

Are you using `glm-10b` or `glm-10b-chinese`? The problem might be caused by using the tokenizer of one model and the checkpoint of the other model. Can you check that you downloaded the correct files belonging to the same repo?

**Comment by ouyangliqi** [comment]
I see, thanks.

**Comment by ouyangliqi** [comment]
Sorry, I still want to confirm that should we repeat the input?

For example, which one is the correct input and target for the model?

```
inputs = "Tsinghua [gMASK] University is located in Beijing."  
targets = "Tsinghua University is located in Beijing."
```
or 
```
inputs = "Tsinghua [gMASK]"  
targets = "Tsinghua University is located in Beijing."
```

**Comment by duzx16** [comment]
Neither.
The correct form is 
```
inputs = "Tsinghua [gMASK]"  
targets = " University is located in Beijing."
```

**Comment by ouyangliqi** [comment]
Thanks!
