### ISSUE TITLE
GLM-10B chinese and MP_SIZE= 2  for pretrain just stay in the function of get_train_val_test_data ?

### ISSUE THREAD

**Issue by LovesportsMcDull** [THUDM/GLM#85]

**Comment by ylfzr** [comment]
Hello, 

Have you addressed the problem? I also found the pretraining procedure gets stuck when setting mp_size > 1 and loader_scatter > 1.

**Comment by LovesportsMcDull** [comment]
&nbsp;&nbsp;&nbsp; You can try adding "cpu_offload":true in the config/config_block_10B*.json and remove the parameter of loader_scatter n in the ds_block_10B*.sh.

&nbsp;&nbsp;&nbsp; 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/GLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 凌晨1:09
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [THUDM/GLM] GLM-10B chinese and MP_SIZE= 2  for pretrain just stay in the function of get_train_val_test_data ? (Issue #85)





 
Hello,
 
Have you addressed the problem? I also found the pretraining procedure gets stuck when setting mp_size &gt; 1 and loader_scatter &gt; 1.

**Comment by ylfzr** [comment]
Got it, thanks.

But it is still strange that mp and loader_scatter can not work together.
