### ISSUE TITLE
ImportError: cannot import name 'torch_required' from 'transformers.utils'

### ISSUE THREAD

**Issue by sh0416** [THUDM/GLM#86]
```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("BAAI/glm-2b", trust_remote_code=True)
```

Transformers version: 4.26.0

**Comment by duzx16** [comment]
Fixed by removing `torch_required` in the code. `torch_required` existed in transformers 4.23.0 but was removed in the following version.

**Comment by sh0416** [comment]
I've just downgrade the transformers version.
Maybe the owner of huggingface hub repository would be do this.
