### ISSUE TITLE
生成结果“随机性固定”的问题

### ISSUE THREAD

**Issue by yipintiancheng** [THUDM/GLM#87]
是否有办法控制“随机性”，使得运行`generate_block.sh`时**使用相同的prompt**可以有不同的结果？
我的意思是，虽然连续**使用相同的prompt**可以获得不同的结果，但是这个结果生成的顺序似乎是固定的。如果我关闭服务重新启动，**提问相同的问题**会得到之前顺序一样的答案，这通过修改`--seed`也无法解决。

**Comment by duzx16** [comment]
之前的代码在加载checkpoint的时候会同时加载random state，然后会覆盖通过`--seed`设置的随机数种子。最新的commit修复了这一点，可以pull最新的代码来解决这个问题。

**Comment by yipintiancheng** [comment]
感谢您的回复！
