### ISSUE TITLE
MPU module

### ISSUE THREAD

**Issue by Ant0082** [THUDM/GLM#89]
I have a question about DeepSpeed. Where can I look up the usage of the APIs for the various methods in the MPU module when developing a model? Are there any documents available or do I need to look at the DeepSpeed source code and try it out myself?

**Comment by duzx16** [comment]
The MPU module is implemented by Megatron-LM (https://github.com/NVIDIA/Megatron-LM), not DeepSpeed. Unfortunately, the library hasn't provided any detailed documents. To understand the methods, you also need to read the Megatron's model parallelism paper (http://arxiv.org/abs/1909.08053)

**Comment by Ant0082** [comment]
> The MPU module is implemented by Megatron-LM (https://github.com/NVIDIA/Megatron-LM), not DeepSpeed. Unfortunately, the library hasn't provided any detailed documents. To understand the methods, you also need to read the Megatron's model parallelism paper (http://arxiv.org/abs/1909.08053)

OK. Thanks for your response.
