### ISSUE TITLE
使用ds_pretrain_nvidia.sh后模型生成异常

### ISSUE THREAD

**Issue by yipintiancheng** [THUDM/GLM#94]
我使用一个**小数据集**通过`ds_finetune_seq2seq.sh`微调后模型达到了预期的效果。但是我在尝试使用这个**小数据集**通过`ds_pretrain_nvidia.sh`预训练时，尽管模型权重顺利保存，这个重新预训练的模型会生成乱码无法使用。我没有找到微调有冻结参数的步骤，它和预训练一样更新了模型全部的参数，我尝试把预训练的**学习率**设置的**和微调一样小**也没有改善。
请问您觉得预训练可能的问题在哪里？是数据集太小的原因吗，或者某些可能不合理的参数设置

**Comment by duzx16** [comment]
微调和预训练的objective是不一样的。微调的objective是给定source生成target，预训练的objective是在一段文本里面预测若干个随机选择的span。不过即使是这样，预训练的模型也不应该生成乱码。是不是用`ds_pretrain_nvidia.sh`的时候没有正确地加载checkpoint？

**Comment by yipintiancheng** [comment]
感谢您的回复！那我应该优先排查加载checkpoint的环节，而不是调整训练参数和数据集的大小

**Comment by zhangzai666** [comment]
> 微调和预训练的objective是不一样的。微调的objective是给定source生成target，预训练的objective是在一段文本里面预测若干个随机选择的span。不过即使是这样，预训练的模型也不应该生成乱码。是不是用`ds_pretrain_nvidia.sh`的时候没有正确地加载checkpoint？

请问您预训练的数据集可以参考一下么
