### ISSUE TITLE
请问GLM模型是否可以生成长句子？我对模型进行推理或者微调的时候都会报出维度不匹配的错误

### ISSUE THREAD

**Issue by taofennanhai** [THUDM/GLM#99]
![{5)J)(B58(Q}ZB AXETBQ}G](https://user-images.githubusercontent.com/44886954/221500863-58875512-8151-4a05-bbbe-a84257a6caaf.png)
![CCZORCJ9E60WW$4FY{Z~RYN](https://user-images.githubusercontent.com/44886954/221500959-0acd002e-0378-4f2e-b2e4-b9aadbeba33a.png)

**Comment by duzx16** [comment]
可以生成长句子，生成的时候应该用model.generate(**inputs, max_length=512, eos_token_id=tokenizer.eop_token_id)

**Comment by taofennanhai** [comment]
感谢你的回复。我还有一个问题就是如何用transformer的GLM模型向微调GPT2那样，微调一个个的长句子？

**Comment by duzx16** [comment]
同样的在https://github.com/THUDM/GLM#generation的training部分提供了计算生成loss的方法
